name: "preprocessing"
backend: "python"

input [
  {
    name: "audio"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

output [
  {
    name: "input_features"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]
